### ISSUE TITLE
`Previous TFC Urls` list can get really messy if the URLs are too long in Gitlab

### ISSUE THREAD

**Issue by ahinh43** [zapier/tfbuddy#34]
This is just a minor cosmetic issue but when the TFC run URLs are too long then Gitlab actually doesn't parse them in a line format. This can typically happen if the workspace name is too long like `aws-account-my-team-is-amazing-and-i-like-donuts` which can lengthen the url.

URLs can show up like this (note that I removed the actual workspace name, but the new length is similar to what it actually is):

![image](https://github.com/zapier/tfbuddy/assets/14356001/393dfbaa-c93b-4dc7-923d-9976a1a5bce3)

I'm thinking we can probably strip out the URL itself and use markdown formatting to link just the run ID to the TFC run URL. Possibly in a table format?

**Comment by polyrain** [comment]
Yeah, @ahinh43 if you could take a look at this it'd be appreciated; this was done as part of a hackathon sort of thing so there's definitely things to iron out with it. Let me know if you need any assistance.
